---
- name: Create glance database
  mysql_db:
    # login_user: "root"
    # login_password: "{{ mysql_password_root }}"
    name: "{{ glance_db_name }}"
    state: "present"
- name: Create glance database user
  mysql_user:
    # login_user: "root"
    # login_password: "{{ mysql_password_root }}"
    name: "{{ glance_db_user}}"
    password: "{{ glance_db_password }}"
    priv: "{{ glance_db_name }}.*:ALL"
    state: "present"
    host: "{{ item }}"
  with_items: '{{hosts}}'
