---
- name: Create glance user
  keystone:
    command: "ensure_user"
    user_name: "{{ glance_service_user }}"
    password: "{{ glance_service_password }}"
    domain_name: "{{ user_domain_name }}"
    project_name: "{{ glance_service_project }}"
    login_user: "{{ keystone_admin_user }}"
    login_user_domain_name: "{{ user_domain_name }}"
    login_project_name: "{{ keystone_admin_project }}"
    login_project_domain_name: "{{ user_domain_name }}"
    login_password: "{{ keystone_admin_password }}"
    endpoint: "http://{{ controller_address }}:35357/v3"
- name: add role for glance
  keystone:
    command: "ensure_user_role"
    user_name: "{{ glance_service_user }}"
    project_name: "{{ glance_service_project }}"
    role_name: "admin"
    login_user: "{{ keystone_admin_user }}"
    login_user_domain_name: "{{ user_domain_name }}"
    login_project_name: "{{ keystone_admin_project }}"
    login_project_domain_name: "{{ user_domain_name }}"
    login_password: "{{ keystone_admin_password }}"
    endpoint: "http://{{ controller_address }}:35357/v3"
- name: create glance service
  keystone:
    command: "ensure_service"
    service_name: "{{ glance_service_name }}"
    service_type: "{{ glance_service_type }}"
    login_user: "{{ keystone_admin_user }}"
    login_user_domain_name: "{{ user_domain_name }}"
    login_project_name: "{{ keystone_admin_project }}"
    login_project_domain_name: "{{ user_domain_name }}"
    login_password: "{{ keystone_admin_password }}"
    endpoint: "http://{{ controller_address }}:35357/v3"
- name: create image service's endpoints
  keystone:
    command: "ensure_endpoint"
    region_name: "{{ glance_service_region }}"
    service_name: "{{ glance_service_name }}"
    service_type: "{{ glance_service_type }}"
    endpoint_list:
      - url: "http://{{ controller_address }}:9292"
        interface: "public"
      - url: "http://{{ controller_address }}:9292"
        interface: "admin"
      - url: "http://{{ controller_address }}:9292"
        interface: "internal"
    login_user: "{{ keystone_admin_user }}"
    login_user_domain_name: "{{ user_domain_name }}"
    login_project_name: "{{ keystone_admin_project }}"
    login_project_domain_name: "{{ user_domain_name }}"
    login_password: "{{ keystone_admin_password }}"
    endpoint: "http://{{ controller_address }}:35357/v3"
