---
- name: Create cinder user
  keystone:
    command: "ensure_user"
    user_name: "{{ cinder_service_user }}"
    password: "{{ cinder_service_password }}"
    domain_name: "{{ user_domain_name }}"
    project_name: "{{ cinder_service_project }}"
    login_user: "{{ keystone_admin_user }}"
    login_user_domain_name: "{{ user_domain_name }}"
    login_project_name: "{{ keystone_admin_project }}"
    login_project_domain_name: "{{ user_domain_name }}"
    login_password: "{{ keystone_admin_password }}"
    endpoint: "http://{{ controller_address }}:35357/v3"
- name: add role for cinder
  keystone:
    command: "ensure_user_role"
    user_name: "{{ cinder_service_user }}"
    project_name: "{{ cinder_service_project }}"
    role_name: "admin"
    login_user: "{{ keystone_admin_user }}"
    login_user_domain_name: "{{ user_domain_name }}"
    login_project_name: "{{ keystone_admin_project }}"
    login_project_domain_name: "{{ user_domain_name }}"
    login_password: "{{ keystone_admin_password }}"
    endpoint: "http://{{ controller_address }}:35357/v3"
- name: create cinderv1 service
  keystone:
    command: "ensure_service"
    service_name: "{{ cinderv1_service_name }}"
    service_type: "{{ cinderv1_service_type }}"
    login_user: "{{ keystone_admin_user }}"
    login_user_domain_name: "{{ user_domain_name }}"
    login_project_name: "{{ keystone_admin_project }}"
    login_project_domain_name: "{{ user_domain_name }}"
    login_password: "{{ keystone_admin_password }}"
    endpoint: "http://{{ controller_address }}:35357/v3"
- name: create cinderv2 service
  keystone:
    command: "ensure_service"
    service_name: "{{ cinderv2_service_name }}"
    service_type: "{{ cinderv2_service_type }}"
    login_user: "{{ keystone_admin_user }}"
    login_user_domain_name: "{{ user_domain_name }}"
    login_project_name: "{{ keystone_admin_project }}"
    login_project_domain_name: "{{ user_domain_name }}"
    login_password: "{{ keystone_admin_password }}"
    endpoint: "http://{{ controller_address }}:35357/v3"
- name: create volumev1 service's endpoints
  keystone:
    command: "ensure_endpoint"
    region_name: "{{ cinder_service_region }}"
    service_name: "{{ cinderv1_service_name }}"
    service_type: "{{ cinderv1_service_type }}"
    endpoint_list:
      - url: "http://{{ controller_address }}:8776/v1/%(tenant_id)s"
        interface: "public"
      - url: "http://{{ controller_address }}:8776/v1/%(tenant_id)s"
        interface: "admin"
      - url: "http://{{ controller_address }}:8776/v1/%(tenant_id)s"
        interface: "internal"
    login_user: "{{ keystone_admin_user }}"
    login_user_domain_name: "{{ user_domain_name }}"
    login_project_name: "{{ keystone_admin_project }}"
    login_project_domain_name: "{{ user_domain_name }}"
    login_password: "{{ keystone_admin_password }}"
    endpoint: "http://{{ controller_address }}:35357/v3"
- name: create volumev2 service's endpoints
  keystone:
    command: "ensure_endpoint"
    region_name: "{{ cinder_service_region }}"
    service_name: "{{ cinderv2_service_name }}"
    service_type: "{{ cinderv2_service_type }}"
    endpoint_list:
      - url: "http://{{ controller_address }}:8776/v2/%(tenant_id)s"
        interface: "public"
      - url: "http://{{ controller_address }}:8776/v2/%(tenant_id)s"
        interface: "admin"
      - url: "http://{{ controller_address }}:8776/v2/%(tenant_id)s"
        interface: "internal"
    login_user: "{{ keystone_admin_user }}"
    login_user_domain_name: "{{ user_domain_name }}"
    login_project_name: "{{ keystone_admin_project }}"
    login_project_domain_name: "{{ user_domain_name }}"
    login_password: "{{ keystone_admin_password }}"
    endpoint: "http://{{ controller_address }}:35357/v3"
