---
- name: Install openstack on controller node
  hosts: controller
  remote_user: vagrant
  roles:
    - ops_packages
    - ntp
    - mysql
    - rabbitmq
    - keystone
    - glance
    - nova
    - neutron-controller
    - horizon
    - heat
    - cinder
    - sahara
- name: Install openstack on compute nodes
  hosts: compute
  remote_user: vagrant
  roles:
    - ops_packages
    - ntp
    - nova-compute
    - neutron-compute
