---
- name: Create neutron database
  mysql_db:
    # login_user: "root"
    # login_password: "{{ mysql_password_root }}"
    name: "{{ neutron_db_name }}"
    state: "present"
- name: Create neutron database user
  mysql_user:
    # login_user: "root"
    # login_password: "{{ mysql_password_root }}"
    name: "{{ neutron_db_user}}"
    password: "{{ neutron_db_password }}"
    priv: "{{ neutron_db_name }}.*:ALL"
    state: "present"
    host: "{{ item }}"
  with_items: '{{hosts}}'
