---
- name: Configure net forward for all VMs
  sysctl: name="net.ipv4.ip_forward" value=1  sysctl_set=yes
- name: Configure net filter
  sysctl: name="net.ipv4.conf.all.rp_filter" value=0 sysctl_set=yes
- name: configure net filer
  sysctl: name="net.ipv4.conf.default.rp_filter" value=0 sysctl_set=yes
- name: Install neutron components for self service network  using Openvswitch
  apt: name={{ item }} state=present
  with_items:
    - neutron-server
    - neutron-plugin-ml2
    - neutron-plugin-openvswitch-agent
    - neutron-l3-agent
    - neutron-dhcp-agent
    - neutron-metadata-agent
    - python-neutron
    - python-neutronclient
    - ipset
- name: configure L2 Agent
  template: src="ml2_conf.ini.j2" dest="/etc/neutron/plugins/ml2/ml2_conf.ini" mode=0644
  notify:
    - restart neutron-openvswitch-agent
- name: Configure openvswitch
  template: src="openvswitch_agent.ini.j2" dest="/etc/neutron/plugins/ml2/openvswitch_agent.ini" mode=0644
  notify:
    - restart neutron-openvswitch-agent
- name: Configure dhcp
  template: src="dhcp_agent.ini.j2" dest="/etc/neutron/dhcp_agent.ini" mode=0644
  notify:
    - restart neutron-dhcp-agent
- name: configure l3-agent
  template: src="l3_agent.ini.j2" dest="/etc/neutron/l3_agent.ini" mode=0644
  notify:
    - restart neutron-l3-agent
- name: configure metdata-agent
  template: src="metadata_agent.ini.j2" dest="/etc/neutron/metadata_agent.ini" mode=0644
  notify:
    - restart neutron-metadata-agent
- name: Configure neutron-server
  template: src="neutron.conf.j2" dest="/etc/neutron/neutron.conf" mode=0644
  notify:
    - restart neutron-server
    - restart nova-api
- name: populate database
  command: |
    su -s /bin/sh -c "neutron-db-manage --config-file /etc/neutron/neutron.conf \
    --config-file /etc/neutron/plugins/ml2/ml2_conf.ini upgrade head" neutron
  no_log: True
