---
- name: Create neutron user
  keystone:
    command: "ensure_user"
    user_name: "{{ neutron_service_user }}"
    password: "{{ neutron_service_password }}"
    domain_name: "{{ user_domain_name }}"
    project_name: "{{ neutron_service_project }}"
    login_user: "{{ keystone_admin_user }}"
    login_user_domain_name: "{{ user_domain_name }}"
    login_project_name: "{{ keystone_admin_project }}"
    login_project_domain_name: "{{ user_domain_name }}"
    login_password: "{{ keystone_admin_password }}"
    endpoint: "http://{{ controller_address }}:35357/v3"
- name: add role for neutron
  keystone:
    command: "ensure_user_role"
    user_name: "{{ neutron_service_user }}"
    project_name: "{{ neutron_service_project }}"
    role_name: "admin"
    login_user: "{{ keystone_admin_user }}"
    login_user_domain_name: "{{ user_domain_name }}"
    login_project_name: "{{ keystone_admin_project }}"
    login_project_domain_name: "{{ user_domain_name }}"
    login_password: "{{ keystone_admin_password }}"
    endpoint: "http://{{ controller_address }}:35357/v3"
- name: create neutron service
  keystone:
    command: "ensure_service"
    service_name: "{{ neutron_service_name }}"
    service_type: "{{ neutron_service_type }}"
    login_user: "{{ keystone_admin_user }}"
    login_user_domain_name: "{{ user_domain_name }}"
    login_project_name: "{{ keystone_admin_project }}"
    login_project_domain_name: "{{ user_domain_name }}"
    login_password: "{{ keystone_admin_password }}"
    endpoint: "http://{{ controller_address }}:35357/v3"
- name: create networking service's endpoints
  keystone:
    command: "ensure_endpoint"
    region_name: "{{ neutron_service_region }}"
    service_name: "{{ neutron_service_name }}"
    service_type: "{{ neutron_service_type }}"
    endpoint_list:
      - url: "http://{{ controller_address }}:9696"
        interface: "public"
      - url: "http://{{ controller_address }}:9696"
        interface: "admin"
      - url: "http://{{ controller_address }}:9696"
        interface: "internal"
    login_user: "{{ keystone_admin_user }}"
    login_user_domain_name: "{{ user_domain_name }}"
    login_project_name: "{{ keystone_admin_project }}"
    login_project_domain_name: "{{ user_domain_name }}"
    login_password: "{{ keystone_admin_password }}"
    endpoint: "http://{{ controller_address }}:35357/v3"
