---
- name: Install Openstack Dashboard
  apt: name="openstack-dashboard" state="present"
- name: configure openstack dashboard
  template: src="local_settings.py.j2" dest="/etc/openstack-dashboard/local_settings.py" mode=0644
  notify:
    - restart apache
# - name: Install Opentack "{{ openstack_version }}" successful
#   debug: msg="Access Openstack at: http://{{ controller_address }}/horizon"
