---
- name: Create nova database
  mysql_db:
    name: "{{ nova_db_name }}"
    state: "present"
- name: Create nova database user
  mysql_user:
    name: "{{ nova_db_user}}"
    password: "{{ nova_db_password }}"
    priv: "{{ nova_db_name }}.*:ALL"
    state: "present"
    host: "{{ item }}"
  with_items: '{{hosts}}'
- name: Create nova-api database
  mysql_db:
    name: "{{ nova_api_db_name }}"
    state: "present"
- name: Create nova_api database user
  mysql_user:
    name: "{{ nova_api_db_user}}"
    password: "{{ nova_api_db_password }}"
    priv: "{{ nova_api_db_name }}.*:ALL"
    state: "present"
    host: "{{ item }}"
  with_items: '{{hosts}}'
